// Shared content for the real site (plain JS, no React).
window.SITE_CONTENT = {
  name: { en: "Kitae (Joseph) Kim", kr: "김기태 (Joseph)" },
  nameShort: { en: "Kitae Kim", kr: "김기태" },
  firstName: { en: "Kitae", kr: "김기태" },
  lastName: { en: "(Joseph) Kim.", kr: "Joseph." },
  tagline: {
    en: "Researcher studying human–AI delegation and the interfaces that keep people in the loop.",
    kr: "사람과 AI가 함께 일할 때, 주도권을 어떻게 나눌지 고민하는 연구자예요.",
  },
  location: { en: "Seoul, KR → Santa Barbara, US · 2026", kr: "서울 → 산타바바라 · 2026" },
  locationShort: { en: "Seoul, KR", kr: "서울, 대한민국" },
  status: {
    en: [
      { label: "Now", value: "M.S., Seoul National University" },
      { label: "Fall 2026", value: "Incoming Ph.D., UC Santa Barbara CS" },
      { label: "Advisor", value: "Prof. Bongwon Suh (SNU)" },
    ],
    kr: [
      { label: "현재", value: "서울대학교 인공지능 협동과정 석사과정" },
      { label: "2026 Fall", value: "UC Santa Barbara CS 박사과정 입학 예정" },
      { label: "지도교수", value: "서봉원 교수님 (SNU)" },
    ],
  },
  email: "joseph423@snu.ac.kr",
  links: [
    { key: "email",    label: "Email",    value: "joseph423@snu.ac.kr", href: "mailto:joseph423@snu.ac.kr", copy: "joseph423@snu.ac.kr" },
    { key: "github",   label: "GitHub",   value: "githae1337",          href: "https://github.com/githae1337" },
    { key: "linkedin", label: "LinkedIn", value: "Kitae Kim",           href: "https://linkedin.com/" },
    { key: "cv",       label: "CV",       value: "PDF ↓",                href: "assets/Kitae_Kim_CV.pdf" },
  ],
  about: {
    en: [
      "I'm a human–computer interaction researcher working at the intersection of AI systems and interface design. My research asks how people can hand tasks to AI agents while keeping meaningful agency — the ability to understand, trust, and redirect what the system is doing.",
      "Lately I've been especially curious about three threads: how users build mental models of what an AI can (and can't) do, what interface cues help them calibrate trust in real time, and how delegation shifts when multiple humans and agents have to coordinate.",
      "Before my current research, I studied Computer Science and Information Science & Culture at SNU. I've been lucky to work across academic labs (HCI Lab at SNU) and industry research (NCSOFT Game AI Lab, Samsung Health H/W, SK Telecom AI Fellowship).",
    ],
    kr: [
      "저는 HCI 연구자로, AI 시스템과 인터페이스 디자인이 만나는 지점에서 연구하고 있어요. 사람이 AI 에이전트에게 일을 맡기면서도 의미 있는 주도권 — 시스템이 무엇을 하는지 이해하고, 신뢰하고, 필요할 때 방향을 바꿀 수 있는 능력 — 을 어떻게 지킬 수 있을지가 제 연구의 큰 줄기예요.",
      "요즘 특히 관심 있는 세 가지 흐름이 있어요. 사용자가 AI의 능력에 대해 어떤 심적 모델을 만드는지, 어떤 인터페이스 신호가 실시간 신뢰 보정에 도움이 되는지, 그리고 여러 사람과 에이전트가 함께 일할 때 위임의 동학이 어떻게 달라지는지.",
      "지금 연구 전에는 서울대학교에서 컴퓨터공학과 정보문화학을 공부했어요. 학교 연구실(SNU HCI Lab), 그리고 산업 연구 (NCSOFT Game AI Lab, Samsung Health H/W, SK Telecom AI Fellowship) 를 오가며 일할 기회가 있었습니다.",
    ],
  },
  interests: {
    en: [
      "Human–AI delegation & trust calibration",
      "Mental models of AI capability",
      "Multi-agent collaboration interfaces",
      "On-device VLM agents for mobile GUI automation",
    ],
    kr: [
      "Human–AI 위임과 신뢰 보정",
      "AI 능력에 대한 심적 모델",
      "다중 에이전트 협업 인터페이스",
      "온디바이스 VLM 기반 모바일 GUI 자동화",
    ],
  },
  news: {
    en: [
      { date: "Oct 2025", body: "Accepted to UC Santa Barbara CS Ph.D. program for Fall 2026 — beyond excited to join the human-centered AI community there." },
      { date: "Oct 2025", body: "Wrapped up the SK Telecom AI Fellowship — shipped an on-device VLM-based GUI operator agent with adaptive exception handling." },
      { date: "Oct 2025", body: "Volunteered at UIST 2025 — great week of hallway conversations about agents and interaction." },
      { date: "Sep 2025", body: "Submitted \"When More Humans Mean Less Cooperation\" to AAMAS 2026 (under review) — non-linear effects of team composition in human–AI public goods games." },
      { date: "Jun 2025", body: "TA'd the Samsung DS2 Program (13th cohort) LLM/RAG course — covered LangChain, LangGraph, MCP." },
      { date: "May 2024", body: "Chatbot customization paper presented at CHI 2024 (Extended Abstracts)." },
      { date: "Oct 2023", body: "OTT drama viewer paper presented at CSCW 2023." },
    ],
    kr: [
      { date: "2025.10", body: "UC Santa Barbara 컴퓨터과학 박사과정 (2026 Fall) 합격 — 정말 기쁘게도 사람 중심 AI 커뮤니티에 합류하게 되었어요." },
      { date: "2025.10", body: "SK Telecom AI Fellowship 종료 — 온디바이스 VLM 기반 GUI 오퍼레이터 에이전트와 적응형 예외 처리 시스템을 만들었어요." },
      { date: "2025.10", body: "UIST 2025 학생 자원봉사자로 참여 — 에이전트와 인터랙션에 대한 좋은 대화들이 많았어요." },
      { date: "2025.09", body: "\"When More Humans Mean Less Cooperation\" AAMAS 2026 투고 (심사 중) — 인간-AI 공공재 게임에서 팀 구성의 비선형 효과." },
      { date: "2025.06", body: "Samsung DS2 Program 13기 LLM/RAG 과정 조교 — LangChain, LangGraph, MCP 실습 지원." },
      { date: "2024.05", body: "챗봇 커스터마이제이션 논문 CHI 2024 (Extended Abstracts) 발표." },
      { date: "2023.10", body: "OTT 드라마 시청자 논문 CSCW 2023 발표." },
    ],
  },
  publications: [
    {
      id: "aamas2026",
      title: "When More Humans Mean Less Cooperation: Non-Linear Effects of Team Composition in Human-AI Public Goods Games",
      authors: [
        { name: "Junghwan Kim" }, { name: "Dongseok Heo" },
        { name: "Kitae Kim", me: true }, { name: "Jung Lee" }, { name: "Bongwon Suh" },
      ],
      venue: "AAMAS 2026",
      venueNote: "under review",
      year: "2026",
      pdf: null,
      abstract: {
        en: "A real-time public goods game with 40 participants across all possible human–AI team ratios (4:0, 3:1, 2:2, 1:3). We find that humans exploit AI partners when teams are balanced but take on leadership roles when they are outnumbered — a non-linear effect that challenges linear assumptions about team composition. The study also surfaces how trust, accountability, and agency shift as the balance between humans and agents changes.",
        kr: "40명이 참여한 실시간 공공재 게임 연구. 인간:AI 비율을 4:0, 3:1, 2:2, 1:3으로 바꿔가며 관찰한 결과, 균형 팀에서는 인간이 AI를 이용하고, 수적으로 열세일 때는 리더 역할을 맡는 비선형 패턴이 나타났어요. 팀 구성이 신뢰·책임·주도권에 어떤 영향을 주는지에 대한 기존 선형 가정에 도전하는 결과예요.",
      },
    },
    {
      id: "chi2024",
      title: "Exploring the Impact of User-Participated Customization in Experiencing Chatbot Failure",
      authors: [
        { name: "Hyungwoo Song" }, { name: "Kyusik Kim" },
        { name: "Kitae Kim", me: true }, { name: "Jeongwoo Ryu" }, { name: "Bongwon Suh" },
      ],
      venue: "CHI 2024",
      venueNote: "Extended Abstracts",
      year: "2024",
      pdf: "assets/CHI2024_Chatbot_Customization.pdf",
      abstract: {
        en: "Traditionally, personalized AI systems have offered customized experiences by inferring user preferences from their system usage data, which can be referred to as data-driven personalization. With the advent of GPTs, opportunities for users to directly engage in the customization process have increased, which we term user-participated customization. In this study, we explored the impact of user-participated customization on user reactions to chatbot failures. We involved twenty-two participants in total, with fourteen for user-participated customization and eight for data-driven personalization. Both groups experienced frustration with chatbot failures, yet their responses differed. Those who customized their chatbots predominantly displayed retrying intentions, in contrast to those using pre-personalized chatbots, who primarily showed giving-up intentions. Moreover, we noted different customizations were preferred for task-oriented and social-oriented chatbots. This study suggests that user-participated customization has the potential to foster the Ikea effect. This effect is expected to mitigate negative experiences with chatbots.",
        kr: "기존의 개인화된 AI 시스템은 시스템 사용 데이터로부터 사용자 선호를 추론해 맞춤 경험을 제공해왔고, 이를 데이터 기반 개인화(data-driven personalization)라 부를 수 있습니다. GPT의 등장과 함께 사용자가 커스터마이제이션 과정에 직접 참여할 기회가 늘었는데, 본 연구에서는 이를 사용자 참여형 커스터마이제이션(user-participated customization)이라 칭합니다. 본 연구는 사용자 참여형 커스터마이제이션이 챗봇 실패 상황에서의 사용자 반응에 미치는 영향을 탐구했습니다. 총 22명의 참가자 중 14명은 사용자 참여형 커스터마이제이션 그룹, 8명은 데이터 기반 개인화 그룹으로 나누어 연구를 진행했습니다. 두 그룹 모두 챗봇 실패에 좌절감을 느꼈으나, 반응은 달랐습니다. 챗봇을 직접 커스터마이즈한 그룹은 주로 재시도 의향을 보인 반면, 사전 개인화된 챗봇을 사용한 그룹은 주로 포기 의향을 나타냈습니다. 또한 과업 지향 챗봇과 사회적 상호작용 지향 챗봇에서 선호되는 커스터마이제이션이 달랐습니다. 본 연구는 사용자 참여형 커스터마이제이션이 IKEA 효과를 유도할 가능성을 제시하며, 이는 챗봇과의 부정적 경험을 완화하는 데 기여할 것으로 기대됩니다.",
      },
    },
    {
      id: "cscw2023",
      title: "Design to Increase Social Interaction between Viewers of Dramas on OTT Platforms",
      authors: [
        { name: "Kitae Kim", me: true }, { name: "Nayoung Hong" },
        { name: "Jiwon Park" }, { name: "Hajin Lim" },
      ],
      venue: "CSCW 2023",
      venueNote: "Companion",
      year: "2023",
      pdf: "assets/CSCW2023_OTT_Drama.pdf",
      abstract: {
        en: "In this paper, we examined the effect of Over-the-Top (OTT) media platforms on social interaction and the sense of connection among drama viewers. The findings from semi-structured interviews revealed that the personalized and asynchronous nature of OTT streaming could lead to reduced social communication opportunities before, during, and after drama-viewing experiences. In particular, participants expressed difficulties in finding companions to co-watch dramas, a lack of simultaneous emotional communication with others, and concerns about spoilers. To address these challenges, we proposed three solution ideas and evaluated them in follow-up interviews. Based on our findings, we discuss design implications for promoting social interaction between OTT drama viewers.",
        kr: "본 논문에서는 OTT(Over-the-Top) 미디어 플랫폼이 드라마 시청자 간의 사회적 상호작용과 연결감에 미치는 영향을 살펴보았습니다. 반구조화 인터뷰 결과, OTT 스트리밍의 개인화되고 비동기적인 특성으로 인해 드라마 시청 전·중·후에 걸친 사회적 소통 기회가 줄어들 수 있음이 드러났습니다. 특히 참가자들은 함께 드라마를 볼 동반자를 찾기 어렵다는 점, 타인과의 실시간 감정 교류가 부족하다는 점, 그리고 스포일러에 대한 우려를 언급했습니다. 이러한 문제를 해결하기 위해 세 가지 솔루션 아이디어를 제안하고 후속 인터뷰를 통해 평가했습니다. 연구 결과를 바탕으로 OTT 드라마 시청자 간의 사회적 상호작용을 촉진하기 위한 디자인 시사점을 논의합니다.",
      },
    },
  ],
  experience: {
    en: [
      { org: "SK Telecom AI Fellowship", role: "Research Intern", date: "May 2025 – Oct 2025",
        desc: "Led design and deployment of an on-device VLM-based GUI Operator Agent with UTG-based navigation and adaptive exception handling for privacy-preserving mobile automation. Qwen2.5-VL, InfiGUI, Gemma-3n, LoRA, Android Accessibility Services." },
      { org: "SNU HCI Lab", role: "Undergraduate Researcher (Prof. Jinwook Seo)", date: "Jan 2023 – Jun 2023",
        desc: "Built a web prototype for app-to-app UI retrieval and design consistency analysis using CLIP embeddings and optimal transport — letting designers compare whole apps, not just screenshots." },
      { org: "NCSOFT Game AI Lab", role: "R&D Center Intern", date: "Jan 2022 – Feb 2022",
        desc: "Developed tutorial-level RL agents for the NetHack Learning Environment and wrote reference documentation for new users." },
      { org: "Samsung Electronics (CE/IM)", role: "Health H/W Intern", date: "Jul 2021 – Aug 2021",
        desc: "Analyzed Galaxy Watch Active 2's HRV accuracy (PPG vs. ECG) and led team ideation for \"Galaxy Blink,\" a camera-based dry eye prevention concept (Creathon Excellence Award)." },
    ],
    kr: [
      { org: "SK Telecom AI Fellowship", role: "Research Intern", date: "2025.05 – 2025.10",
        desc: "온디바이스 VLM 기반 GUI 오퍼레이터 에이전트의 설계와 배포를 주도했어요. UTG 기반 네비게이션과 적응형 예외 처리로 프라이버시를 지키는 모바일 자동화를 목표로. Qwen2.5-VL, InfiGUI, Gemma-3n, LoRA, Android Accessibility Services." },
      { org: "SNU HCI Lab", role: "학부 연구생 (서진욱 교수님)", date: "2023.01 – 2023.06",
        desc: "CLIP 임베딩과 최적 수송(optimal transport)을 활용한 앱 단위 UI 검색·일관성 분석 웹 프로토타입 개발. 스크린샷이 아니라 앱 전체를 비교할 수 있도록." },
      { org: "NCSOFT Game AI Lab", role: "R&D Center 인턴", date: "2022.01 – 2022.02",
        desc: "NetHack Learning Environment용 튜토리얼 수준 강화학습 에이전트 개발과 신규 사용자용 레퍼런스 문서 작성." },
      { org: "삼성전자 (CE/IM)", role: "Health H/W 인턴", date: "2021.07 – 2021.08",
        desc: "Galaxy Watch Active 2의 HRV 정확도 분석 (PPG vs. ECG), 카메라 기반 안구건조증 예방 콘셉트 \"Galaxy Blink\" 팀 기획 리드 (Creathon 우수상 수상)." },
    ],
  },
  ui: {
    sections: {
      home:         { en: "Home",          kr: "홈" },
      about:        { en: "About",         kr: "소개" },
      interests:    { en: "Research",      kr: "연구" },
      news:         { en: "News",          kr: "소식" },
      publications: { en: "Publications",  kr: "논문" },
      experience:   { en: "Experience",    kr: "경력" },
      contact:      { en: "Contact",       kr: "연락처" },
      cv:           { en: "CV",            kr: "CV" },
    },
    pageLabels: {
      about:        { en: "About",          kr: "소개" },
      interests:    { en: "Research Interests", kr: "연구 관심사" },
      news:         { en: "News",           kr: "최근 소식" },
      publications: { en: "Publications",   kr: "논문" },
      experience:   { en: "Research Experience", kr: "연구 경력" },
      contact:      { en: "Contact",        kr: "연락처" },
    },
    contactHeadline: {
      en: "Say hi — I'd love to chat about delegation, agency, or strange interfaces.",
      kr: "편하게 연락 주세요. 위임, 주도권, 이상한 인터페이스 이야기 좋아합니다.",
    },
    footer: {
      en: "© 2026 Kitae (Joseph) Kim · Built for joseph423.github.io",
      kr: "© 2026 김기태 (Joseph) · joseph423.github.io",
    },
    dark:  { en: "Dark",  kr: "다크" },
    light: { en: "Light", kr: "라이트" },
    backToTop: { en: "Back to top", kr: "맨 위로" },
    readMore:  { en: "Read abstract", kr: "요약 읽기" },
    hideAbstract: { en: "Hide abstract", kr: "요약 접기" },
    viewDetail: { en: "Details", kr: "상세" },
    backToPubs: { en: "← Back to publications", kr: "← 논문 목록으로" },
    downloadPdf: { en: "Download PDF", kr: "PDF 다운로드" },
    noPdf: { en: "Not yet available", kr: "아직 공개되지 않음" },
    venue: { en: "Venue", kr: "게재처" },
    authors: { en: "Authors", kr: "저자" },
    abstract: { en: "Abstract", kr: "요약" },
    copyEmail: { en: "Copy email", kr: "이메일 복사" },
    copied: { en: "Copied!", kr: "복사됨!" },
  },
};
